### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by ghost** [nblogist/plasm-faucet-backend#2]
Hi Furqan, I just wanted to let you know that there is currently some CORS issue with the faucet 
![image](https://user-images.githubusercontent.com/17739166/121480368-93e37b80-c9fd-11eb-93ca-d9349575a0b3.png). 

Thanks again for the faucet and your hardwork :)

**Comment by nblogist** [comment]
Hey @STYJ Thanks for letting me know, I'll put it on my todo and get it fixed asap! 
Thank you for acknowledging!

**Comment by ghost** [comment]
Thank you Furqan :)

**Comment by nblogist** [comment]
@STYJ please check now it works now. Please reopen if the issue presisit.
